CREATE TABLE IF NOT EXISTS cs_user (
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL UNIQUE,
    password      VARCHAR(128) NOT NULL,
    nick_name     VARCHAR(64)  NOT NULL,
    roles         VARCHAR(128) NOT NULL,
    status        CHAR(1)      NOT NULL DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS kb_document (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               VARCHAR(200) NOT NULL,
    category            VARCHAR(64)  NOT NULL DEFAULT 'general',
    source              VARCHAR(128) NOT NULL DEFAULT 'ruoyi',
    content             CLOB         NOT NULL,
    status              VARCHAR(16)  NOT NULL DEFAULT 'draft',
    neo4j_document_id   VARCHAR(64),
    chunk_count         INT          DEFAULT 0,
    entity_count        INT          DEFAULT 0,
    create_by           VARCHAR(64),
    create_time         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    update_time         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cs_session (
    session_id    VARCHAR(64) PRIMARY KEY,
    turn_count    INT          DEFAULT 0,
    created_at    VARCHAR(64),
    updated_at    VARCHAR(64),
    sync_time     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cs_turn (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    VARCHAR(64)  NOT NULL,
    role          VARCHAR(16)  NOT NULL,
    content       CLOB,
    intent        VARCHAR(32)  DEFAULT '',
    confidence    DOUBLE       DEFAULT 0,
    created_at    VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS cs_ticket (
    ticket_id     VARCHAR(64) PRIMARY KEY,
    subject       VARCHAR(200),
    detail        CLOB,
    priority      VARCHAR(16)  DEFAULT 'normal',
    status        VARCHAR(16)  DEFAULT 'open',
    session_id    VARCHAR(64)  DEFAULT '',
    assignee      VARCHAR(64)  DEFAULT '',
    remark        VARCHAR(500) DEFAULT '',
    created_at    VARCHAR(64),
    update_time   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
